### ISSUE TITLE
WTRL Teams Processed. Team Name not Found.

### ISSUE THREAD

**Issue by hypeRRRRRR** [jorgezwift/tugazconsole#1]
Hi Jorge,

I can´t find our teams with the "build_template_conf.html"

Do you only call the Zwift Racing League Teams? We want to use your console for the WTRL TTT Events. Is it also possbile to get the TTT Teams? 

Mabye it´s possbile to get in contact with you by e-mail? 

Many thanks,
Tobi

**Comment by jorgezwift** [comment]
The configuracion tool is not working for ZRL.
For WTRL TTT the name should be "(TEAM_TAG)" with the brackets.

**Comment by jorgezwift** [comment]
a new version of tools/build_template_conf.html is available.
